### ISSUE TITLE
Capitalized

### ISSUE THREAD

**Issue by RWOverdijk** [tenry92/orm-js#1]
I was wondering why you capitalized the names of all decorators. Is this some sort of convention I'm not aware of?

**Comment by tenry92** [comment]
Is there a convetion doing it differently? I'm not aware of _any_ convention concerning JavaScript decorators.

**Comment by RWOverdijk** [comment]
@tenry92 Afaik, decorators are lower case as they're functions. Classes are Pascal. I was just curious to find out your logic as I'm building something similar to your module.

**Comment by tenry92** [comment]
Can we see decorators as "functions"? It's something on its own actually. Like constructor functions ("classes") are something on its own as well ;)

**Comment by RWOverdijk** [comment]
Decorators are functions. And those "constructor functions" are called methods. The reside elsewhere (in a class, and not a context). Anyway I got my answer, and I don't feel like arguing semantics. If you don't believe me, look it up :)

Thanks!

**Comment by tenry92** [comment]
I searched the internet for examples / use cases with JavaScript decorators, and I found a few, such as _core-decorators_. Everything I found used the lower case convention.

So, I'll update my decorators to lower case soon. Thank you for calling my attention to it!
